name: Linter
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: npm install eslint --save-dev
      - run: npm install eslint-config-airbnb-base --save-dev
      - run: npm install eslint-plugin-import
      - run: make lint
