name: Linter
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/Nikimad/frontend-project-lvl1.git
      - run: make install
      - run: make lint
